productpage:
  namespace: uat
  image: ghcr.io/mercurial963/bookinfo-productpage
  tag: uat
  replicas: 1
  imagePullSecrets: ghcr-bookinfo-ratings
  port: 9080
  healthCheckPath: "/health"
ingress:
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
  # host: bookinfo.uat.opsta.co.th
  # path: "/student[X]/productpage(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  COMMIT_ID: CHANGEME
  DETAILS_HOSTNAME: http://bookinfo-uat-details:9080
  RATINGS_HOSTNAME: http://bookinfo-uat-ratings:8080
  REVIEWS_HOSTNAME: http://bookinfo-uat-reviews:9080